apiVersion: v2
name: counter-backend
version: 0.1.0-ee7f53f927ab38f1a6c97371207d02fb214516e3

dependencies:
  - name: counter-backend
    version: 0.1.0-ee7f53f927ab38f1a6c97371207d02fb214516e3
    repository: "oci://ghcr.io/how-to-devops/charts"

