controller:
  args:
    appResyncPeriod: 30

server:
  service:
    type: NodePort
    nodePortHttp: 30000

configs:
  repositories:
    github:
      url: https://github.com/how-to-devops/gitops
  secret:
    argocdServerAdminPassword: $2a$12$rmt5/gAmHlrmH9LokPewXu02zEYoawUSlsVwI9VbK7ZDqVY48o4sm # argocd